Adds callback to report the download and upload progress
audacity/audacity pull request #1202
Opened 2021-07-01 09:53 UTC by crsib

This is required for the GSoC project on Source Separation to provide a better UX.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"

2021-07-01 13:31 UTC, Paul-Licameli requested changes
One line looks like a mistake, and also the macOS build fails.

2021-07-01 13:31 UTC, Paul-Licameli commented on libraries/lib-network-manager/curl/CurlResponse.cpp
> +       clientp->mUploadProgressCallback(dlnow, dltotal);
Did you mean `ulnow, ultotal`

2021-07-12 13:45 UTC, crsib commented on libraries/lib-network-manager/curl/CurlResponse.cpp
> +       clientp->mUploadProgressCallback(dlnow, dltotal);
Yes, thank you! That is fixed now

2021-07-13 18:46 UTC, Paul-Licameli approved these changes
That was the only issue in my first review.

2021-07-13 18:47 UTC, merged