Try to import as Raw Data when Audacity did not recognize the type of the file(Drag file into audacity case)
audacity/audacity pull request #1920
Opened 2021-10-13 15:30 UTC by cjw1115

Resolves: *(direct link to the issue)*

I'm on windows audio processing related work, and there is a lot of raw audio data is dumped in processing pipe line.
When I want to import those raw data files into audacity, I have to go to file-import-raw data, but I prefer to just drag it into audacity window to parse raw data. so I request this pull-request.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2021-12-07 00:52 UTC, Paul-Licameli requested changes

2021-12-07 00:52 UTC, Paul-Licameli commented on src/import/Import.h
> +   std::tuple<bool, bool> Import( AudacityProject &project,
Rather than return a tuple, define an enumeration of three possible return values.

2021-12-07 00:54 UTC, Paul-Licameli commented
Hello @cjw1115 , if you are still interested in having this pull request merged into the present development branch, then please rebase onto a recent master version, squash the commits into one, and force-push the branch.

I say squash because I see commits that correct errors in previous commits.  I'd rather have that cleaned up.  Not every PR should be done as one commit, but this one is not large enough to require multiple commits for clarity.

2021-12-14 07:17 UTC, cjw1115 commented
@Paul-Licameli Sure, let me update it

2021-12-14 11:02 UTC, Paul-Licameli commented
That's good.  Now, please make the suggested other source code changes.  An enumeration of three possibly return types would be better than a tuple.

2024-10-15 07:55 UTC, LWinterberg commented
Hello! We just [switched master to 4.0.0](https://forum.audacityteam.org/t/master-has-been-switched-to-4-0-0-development/120444) which makes this PR incompatible and/or obsolete as we're switching UI framework and reorganizing large parts of the codebase. You're very welcome to make these kinds of contributions in the future though, after things stabilize a little bit.

2024-10-15 07:55 UTC, closed without merging