Xlisp fixes
audacity/audacity pull request #2459
Opened 2022-01-20 16:17 UTC by Paul-Licameli

Resolves: #2372

It was possible to hang Nyquist with certain inputs to the Nyquist prompt.

This was fun... I had to dive into the XLisp interpreter code.  This changes lib-src, and should be considered by @rbdannenberg for upstreaming to Nyquist.

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2022-01-20 16:29 UTC, rbdannenberg commented
Very interesting -- this may take a few days, since it's surprising this could have been lurking in Xlisp for decades (or maybe there's a branch like Xlispstat where it was detected and fixed alreaady). But I'll definitely look into it. Thanks.

2022-01-20 16:53 UTC, Paul-Licameli commented
> Very interesting -- this may take a few days, since it's surprising this could have been lurking in Xlisp for decades (or maybe there's a branch like Xlispstat where it was detected and fixed alreaady). But I'll definitely look into it. Thanks.

It is not XLisp proper but Nyquist’s additions to it that had the bug.  See the commit comments.

2022-01-22 01:31 UTC, rbdannenberg requested changes
Very interesting! The xlisp.c code does come from original xlisp, although it was split to allow re-entering the interpreter, and I believe it's correct without the added xlend. The reason is that you can only get to top_level by executing xlrestore, which loads the entire heap from a file and sets xlcontext to NULL. This is all disabled in Nyquist because Nyquist allows for "externals" and there's no implementation for archiving and restoring added datatypes, so this code is unreachable. If you call TOP-LEVEL, you unwind to a context with a CF_TOPLEVEL flag, which takes you to some other place.

The rest looks right. I would consider setting xlcontext to NULL when reentering the interpreter, although with xlend() in nyx.c, it shouldn't be necessary.

2022-01-22 22:18 UTC, Paul-Licameli commented
> Very interesting! The xlisp.c code does come from original xlisp, although it was split to allow re-entering the interpreter, and I believe it's correct without the added xlend. The reason is that you can only get to top_level by executing xlrestore, which loads the entire heap from a file and sets xlcontext to NULL. This is all disabled in Nyquist because Nyquist allows for "externals" and there's no implementation for archiving and restoring added datatypes, so this code is unreachable. If you call TOP-LEVEL, you unwind to a context with a CF_TOPLEVEL flag, which takes you to some other place.
> 
> The rest looks right. I would consider setting xlcontext to NULL when reentering the interpreter, although with xlend() in nyx.c, it shouldn't be necessary.

I do not see a function called `xlrestore` in Audacity's version of the xlisp library, only a function called `sound_xlrestore`.

Are you sure this unusual bug isn't present even in the original?  That evaluating `(return)` once is ok (`xlfail` will be invoked) but the second time might hang the interpreter?  But it is unnecessary for Audacity so I can omit that fix.

2022-01-22 22:22 UTC, Paul-Licameli commented
I have amended the pull request.  Please approve it @rbdannenberg if there are no further objections.

2022-01-23 02:25 UTC, rbdannenberg approved these changes

2022-01-23 02:36 UTC, rbdannenberg commented
Sorry, it's xrestore() rather than xlrestore() (in xldmem.c).  It looks like when I added external types, I planned for xrestore() to work, but then decided sound types were too messy to save and restore, so sound_xlrestore() is where the restore implementation would go, but it should never get called. The XLisp RESTORE function is not defined unless SAVERESTORE is defined. 

I tried various returns in command line Nyquist just to make sure, and it seems safe:
```
> (return)
error: no target for RETURN
1> (return)
error: no target for RETURN
2> (top-level)
[ back to top level ]
> (return)
error: no target for RETURN
1> (setf *breakenable* nil)
NIL
1> (top-level)
[ back to top level ]
> (return)
error: no target for RETURN
> (return)
error: no target for RETURN
> 
```

2022-01-23 03:14 UTC, merged