Issue with sound activated recording
audacity/audacity pull request #2567
Opened 2022-02-17 18:23 UTC by pietro68

Resolves: *https://github.com/audacity/audacity/issues/2090*

*see original issue for motivations*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

2022-02-17 18:26 UTC, pietro68 commented
After these changes, I tried the steps in the linked issue and I can not reproduce the bug anymore.
Normal sound-activated recording (i.e. with a normal threshold) still seems to work fine, so previous functionality is preserved.

2022-02-17 21:00 UTC, Paul-Licameli requested changes

2022-02-17 21:00 UTC, Paul-Licameli commented on src/toolbars/ControlToolBar.cpp
> +   if ( isPaused )
This fix is not conservative enough.  The state changes in ProjectAudioManager no longer happen.  All the checks in that function do not happen.

I say, do not change ControlTooBar.  Rather, change ProjectAudioManager.  Make it inherit wxEvtHandler.  Then let it receive idle events from the application, similar to this other line in SpectralDataDialog.cpp:

```
   wxTheApp->Bind(wxEVT_IDLE, &SpectralDataDialogWorker::OnIdle, this);
```

Then let the event handler do all that `OnSoundActivationThreshold` did.  (Except delaying the call to Pause() using CallAfter will not be needed, as you will surely already be on the main thread and in the idle time of the event loop.)

2022-02-18 16:05 UTC, pietro68 commented
Hopefully what you will see in my last commit is what you meant in your suggestion; the problem still persist though (see commit message for details).
I will now try something different on top of this commit.

2022-03-02 17:49 UTC, closed without merging