Bugfix: #2948.  Persist Devices preference changes.
audacity/audacity pull request #2952
Opened 2022-05-19 12:48 UTC by ksoze95

Resolves: #2948 

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2022-05-20 08:09 UTC, Paul-Licameli requested changes

2022-05-20 08:09 UTC, Paul-Licameli commented on src/prefs/DevicePrefs.cpp
> +      AudioIORecordChannels.Commit();
I am not willing to accept this very special case fix of what might be an error of commit d9a873a that introduced SettingsTransaction.  It was not intended that individual settings variables should require commits like this.

Do you instead have an explanation why the line `mTransaction->Commit();` in PrefsDialog.cpp fails to have the effect it should?

Can you investigate, verify that d9a873a is the first bad commit in 3.2 showing this bug?

2022-05-20 10:30 UTC, Paul-Licameli commented
Kit:  I was bothered enough that I debugged this a bit myself.

`AudioIOPlaybackDevice` is written in `DevicePrefs::Commit` and the later `mTransaction->Commit()` in `PrefsDialog::OnOk` should persist the setting but doesn't -- why not?

Because in between, there is re-reading of `AudioIOPlaybackDevice` that destroys the un-committed change, and that's a more general bug in Prefs.h that should be fixed.

See that there are two overloads of `ReadWithDefault`.  One of them is correct in case the settings object already has a value, but the other is incorrect.

2022-05-23 09:33 UTC, Paul-Licameli approved these changes
Very simple!

2022-05-23 09:49 UTC, petersampsonaudacity commented
Testing on W10 with @ksoze95 's latest branch build:  audacity-win-3.2.0-alpha-20220522+2d8ee49-x64-msvc2022 

This is **_not_** working properly:


See  Devices Prefs ignores user settings for changes of I/O devices #2948  for my test results

2022-06-04 15:33 UTC, Paul-Licameli commented
I'm closing this PR and writing a different fix that addresses more fundamental errors in the Preferences system and doesn't contain special case code to write one of the settings.

2022-06-04 15:33 UTC, Paul-Licameli commented
I'm closing this PR and writing a different fix that addresses more fundamental errors in the Preferences system and doesn't contain special case code to write one of the settings.

2022-06-04 15:33 UTC, closed without merging