Make basstreble stateless
audacity/audacity pull request #3628
Opened 2022-09-15 16:52 UTC by pietro68

Resolves: #3626 

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2022-12-08 16:19 UTC, Paul-Licameli commented on src/effects/BassTreble.cpp
> +   auto& ms = GetSettings(settings);;
extra ';'

2022-12-08 16:33 UTC, Paul-Licameli commented on src/effects/BassTreble.cpp
> +   void InstanceInit(EffectSettings& settings, EffectBassTrebleState& data, float sampleRate);
The three functions that follow can also compile as `static`.

2022-12-08 16:44 UTC, Paul-Licameli requested changes
Minor suggestions.  This looks good.

Now, I think we should reenable BassTreble, Phaser, and Wahwah in the side bar.

So add a commit to do that.  Then let QA test those three effects before this is merged.

Echo is another effect that could easily join those three.  The transformation of a PerTrackEffect for realtime support should be a very familiar exercise now.  I suggest that as another near term task.

2022-12-08 17:50 UTC, pietro68 commented on src/effects/BassTreble.cpp
> +   auto& ms = GetSettings(settings);;
ok, done

2022-12-08 17:51 UTC, pietro68 commented on src/effects/BassTreble.cpp
> +   void InstanceInit(EffectSettings& settings, EffectBassTrebleState& data, float sampleRate);
ok, done

2022-12-09 14:15 UTC, Paul-Licameli approved these changes

2022-12-09 14:21 UTC, merged