Disallow adding a destructive, or realtime, effect which has been deleted since application start up.
audacity/audacity pull request #3801
Opened 2022-10-12 15:42 UTC by ksoze95

Resolves: #3719 

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2022-10-14 11:00 UTC, vsverchinsky requested changes
Dialog message text needs translation

2022-10-14 11:00 UTC, vsverchinsky commented on src/RealtimeEffectPanel.cpp
> +         wxMessageBox("This plugin could not be loaded.\nIt may have been deleted.", "Plugin Error");
Please make these strings translatable

2022-10-14 11:00 UTC, vsverchinsky commented on src/effects/EffectUI.cpp
> +      wxMessageBox("This plugin could not be loaded.\nIt may have been deleted.", "Plugin Error");
Same

2022-10-14 23:52 UTC, ksoze95 commented on src/RealtimeEffectPanel.cpp
> +         wxMessageBox("This plugin could not be loaded.\nIt may have been deleted.", "Plugin Error");
Done.

2022-10-14 23:52 UTC, ksoze95 commented on src/effects/EffectUI.cpp
> +      wxMessageBox("This plugin could not be loaded.\nIt may have been deleted.", "Plugin Error");
Done.

2022-10-17 08:18 UTC, vsverchinsky approved these changes

2022-10-17 10:11 UTC, Paul-Licameli commented on src/RealtimeEffectPanel.cpp
> +         wxMessageBox(_("This plugin could not be loaded.\nIt may have been deleted."), _("Plugin Error"));
Use ::AudacityMessageBox

2022-10-17 10:11 UTC, Paul-Licameli requested changes

2022-10-17 10:11 UTC, Paul-Licameli commented on src/effects/EffectUI.cpp
> +      wxMessageBox(_("This plugin could not be loaded.\nIt may have been deleted."), _("Plugin Error"));
Use ::AudacityMessageBox

2022-10-17 10:14 UTC, Paul-Licameli commented on src/effects/EffectUI.cpp
> +      wxMessageBox(_("This plugin could not be loaded.\nIt may have been deleted."), _("Plugin Error"));
Or better, use BasicUI::ShowMessageBox in both places.

2022-10-18 12:50 UTC, ksoze95 commented on src/RealtimeEffectPanel.cpp
> +         wxMessageBox(_("This plugin could not be loaded.\nIt may have been deleted."), _("Plugin Error"));
Replaced wxMessageBox with BasicUI::ShowMessageBox as suggested below.

2022-10-27 11:02 UTC, LWinterberg commented on src/menus/FileMenus.cpp
> +            .Caption(XO("Project Error")));
Let's do
> Window title: Missing Plugins
> This project contains some realtime effect plugins that cannot be found on this system.
> The project may sound different than intended. [Learn more](https://audacityteam.org/errors#missing-plugins)
> [OK]

with the "learn more" having an accessible link to https://audacityteam.org/errors#missing-plugins

2022-11-15 13:02 UTC, LWinterberg approved these changes

2022-12-09 14:31 UTC, Paul-Licameli commented on src/effects/EffectUI.cpp
> +   if (!PluginManager::IsPluginAvailable(*plug))
Should this message be shown also in case `plug` is null?

2022-12-09 14:32 UTC, Paul-Licameli approved these changes
A few suggestions to improve it, but nothing that should block it.

2022-12-19 13:32 UTC, merged