A collection of help, credits and readme things
audacity/audacity pull request #3941
Opened 2022-11-15 10:56 UTC by LWinterberg

Resolves: #3677
Resolves: #3774
Partially resolves: #3922

This PR does  a handful of oddjobs: 
* It removes some mentions of the wiki and offline manual in favor of the online manual and gitbook
* It adds some new folks to the credits and undoes a separation of exmusers and contributors as requested by the tantaman
* It removes the readme.txt and any of its mentions in the installers (replacing it with the readme.md)
* It removes some bits of Dark Audacity-specific help stuff
* (and apparently is also took in a test I made on a different branch because I didn't pay attention from where I branched and now there's a test commit and its revert in here

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR
- [ ] I figured out how to get rid of those bad commits

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2022-11-15 13:29 UTC, Paul-Licameli commented
Did you mean to base this on the master or the release-3.2.2 branch?

2022-11-15 13:40 UTC, LWinterberg commented
Not really, no. Some of these changes update strings and IMHO none of them are high-priority enough to warrant an inclusion in the patch release

2022-12-07 12:48 UTC, crsib requested changes
Please do an interactive rebase to remove "[revert] align Light theme on macOS with Win/Lin" commits

2022-12-27 11:56 UTC, crsib approved these changes

2022-12-27 12:44 UTC, merged