More in lib audio io
audacity/audacity pull request #4221
Opened 2023-01-22 21:51 UTC by Paul-Licameli

Resolves: *(direct link to the issue)*

*(short description of the changes and the motivation to make the changes)*

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

2023-01-24 10:46 UTC, crsib requested changes
I would like to see more descriptive names, please

2023-01-24 11:23 UTC, Paul-Licameli commented on libraries/lib-audio-io/AudioIO.h
> +struct AUDIO_IO_API TransportTracks {
yes

2023-01-24 11:42 UTC, Paul-Licameli commented on libraries/lib-audio-io/ProjectAudioIO.cpp
> +   const std::function<OptionsFactory>
It saves the small bother of qualifying `OptionsFactory` but I will rewrite it

2023-01-24 11:52 UTC, Paul-Licameli commented on libraries/lib-audio-io/ProjectAudioIO.h
> +
ok

2023-01-24 12:37 UTC, crsib approved these changes

2023-01-27 12:44 UTC, Ryan-Miller-Audacity commented
Sanity checked the following items: starting and stopping of playback, recording (including punch-and-roll), monitoring (click in the output meter), play-at-speed button, scrubbing and observed no issues/unwanted behaviors.

2023-01-27 13:22 UTC, merged