Extract lib wx init
audacity/audacity pull request #4334
Opened 2023-02-19 20:07 UTC by Paul-Licameli

Resolves: *(direct link to the issue)*

Extract libraries that are not toolkit neutral but encapsulate what is behind the BasicUI facade and will need corresponding reimplementation against Qt

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

2023-02-21 16:36 UTC, Paul-Licameli commented
The dependency #4313 required rebasing onto recent master and conflict resolution in `#include` directives, and then this one did too, onto that rebasing.

2023-02-22 02:46 UTC, Paul-Licameli commented
And rebased again.

2023-03-03 10:22 UTC, crsib commented on libraries/lib-foo/CMakeLists.txt
> +set( SOURCES
lib-foo is still with us? I think we need lib-bar to, so it doesn't feel lonely xD

2023-03-03 10:23 UTC, crsib commented on libraries/lib-foo/CMakeLists.txt
> -#[[
And now it's gone :-)

2023-03-03 10:24 UTC, crsib commented on src/prefs/LibraryPrefs.cpp
> +<<<<<<< HEAD
Is it expected?

2023-03-03 10:24 UTC, vsverchinsky requested changes

2023-03-03 10:24 UTC, vsverchinsky commented on libraries/lib-foo/CMakeLists.txt
> +   Foo.cpp
Not sure that I understand what this is for

2023-03-03 10:24 UTC, vsverchinsky commented on libraries/lib-foo/CMakeLists.txt
> -   Foo.cpp
Ah, so this was indeed committed by mistake. I guess that this change should be squashed

2023-03-03 10:24 UTC, vsverchinsky commented on src/prefs/LibraryPrefs.cpp
> +<<<<<<< HEAD
This diff shouldn't be there

2023-03-03 10:24 UTC, vsverchinsky commented on src/prefs/LibraryPrefs.cpp
> -<<<<<<< HEAD
Here it is removed, but would be better to squash as we always do

2023-03-03 11:13 UTC, Paul-Licameli commented
Sorry guys, I made mistakes rebasing this one, and did not clean up the intermediate commits correctly.  Expect another force push and I will invite review again.

2023-03-03 12:49 UTC, vsverchinsky approved these changes

2023-03-06 19:04 UTC, Paul-Licameli commented
Rebased onto recent master and resolved conflicts

2023-03-10 00:30 UTC, Paul-Licameli commented
A difficult conflict resolution with e892cea70e50e24dd168a6c13966b4a007761bca

Review again, see new inserted commit

2023-03-13 13:37 UTC, crsib commented
The branch requires conflict resolution now

2023-03-13 19:10 UTC, Paul-Licameli commented
I have rebased and resolved conflicts with the vertial ruler project.  Just a lot of `#include` lines and the list of files in src/CMakeLists.txt.

2023-03-14 10:07 UTC, crsib approved these changes

2023-03-15 15:01 UTC, merged