Variant utilities
audacity/audacity pull request #4535
Opened 2023-04-12 11:26 UTC by Paul-Licameli

Resolves: *(direct link to the issue)*

Utilities to make usage of std::variant easier.

Variant::Visit() now simulates the one-visitor case of C++17 std::visit more exactly according to the standard.

Variant::VariantVisitor is a useful class template for defining visitors.

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

2023-04-12 11:54 UTC, crsib approved these changes
Pretty awesome!

2023-04-12 11:57 UTC, crsib requested changes
I'll like the proposed changes, but GCC does not :-)

2023-04-12 13:11 UTC, Paul-Licameli commented
> I'll like the proposed changes, but GCC does not :-)

It may be GCC isn't doing CTAD correctly and a `make_visitor` function like `make_pair` may be needed after all

2023-04-13 11:45 UTC, Paul-Licameli commented
This idea needed much more work than I thought to get all the details really right.

Please review the whole again from the beginning.

There are also now many more compile-time tests (so we know the cases don't violate the `static_assert`s) and run-time tests of various combinations of values in the visitor, and constness and reference types of the arguments and the expected return value type.

2023-04-14 11:47 UTC, crsib commented on libraries/lib-utility/Variant.h
> +auto TypeCheckedVisitHelperFunction(Visitor &&vis, Variant &&var)
I wonder if `decltype(auto)` is needed here as well

2023-04-14 11:47 UTC, crsib commented on libraries/lib-utility/Variant.h
> +auto TypeCheckedVisitHelperFunction(Visitor &&vis, Variant &&var)
Or, sorry, I have missed the `->` arrow

2023-04-14 11:53 UTC, crsib commented on libraries/lib-utility/Variant.h
> +   typename VariantBase = detail::deduced_variant<Variant &&>>
Pretty cool!

2023-04-14 11:57 UTC, crsib approved these changes
Looks fantastic!

2023-04-16 16:07 UTC, merged