Sample format checks
audacity/audacity pull request #5109
Opened 2023-08-29 17:52 UTC by vsverchinsky

Resolves: #5101 #4752

- [x] I signed [CLA](https://www.audacityteam.org/cla/)
- [x] The title of the pull request describes an issue it addresses
- [x] If changes are extensive, then there is a sequence of easily reviewable commits
- [x] Each commit's message describes its purpose and effects
- [x] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [x] Each commit compiles and runs on my machine without known undesirable changes of behavior

2023-08-30 14:28 UTC, Paul-Licameli commented
macOS build is failing

2023-08-31 09:14 UTC, vsverchinsky commented
> macOS build is failing

Now fixed

2023-08-31 12:09 UTC, Paul-Licameli commented on src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
> +"into a stereo track"),
@LWinterberg

2023-08-31 12:16 UTC, Paul-Licameli commented on libraries/lib-wave-track/WaveTrack.h
> +   sampleFormat mLegacyFormat;
Please duplicate the comment

2023-08-31 12:18 UTC, Paul-Licameli requested changes

2023-08-31 12:18 UTC, Paul-Licameli commented on libraries/lib-wave-track/WaveTrack.cpp
> +   sampleFormat mFormat;
Uninitialized in the default constructor?  Make it `floatSample`

2023-08-31 12:22 UTC, Paul-Licameli commented on libraries/lib-wave-track/WaveTrack.cpp
>  "release of Audacity version 3.4");
@LWinterberg wording?

2023-08-31 12:54 UTC, Paul-Licameli commented
Done reviewing.  Just fix one initialization.

2023-08-31 16:53 UTC, Paul-Licameli approved these changes

2023-08-31 17:52 UTC, vsverchinsky commented
Rebased onto recent master that has fix for misalligned channel, to avoid bugs that are already fixed from being observed

2023-09-05 11:59 UTC, LWinterberg commented on libraries/lib-wave-track/WaveTrack.cpp
>  "release of Audacity version 3.4");
looks good to me

2023-09-05 11:59 UTC, LWinterberg commented on src/tracks/playabletrack/wavetrack/ui/WaveTrackControls.cpp
> +"into a stereo track"),
looks good to me

2023-09-06 14:49 UTC, Paul-Licameli commented
This is approved for merge.  I rebased it onto recent master and made the needed conflict resolutions.

2023-09-06 16:23 UTC, merged