6618 audiocom redirect tagging
audacity/audacity pull request #6635
Opened 2024-06-07 07:42 UTC by saintmatthieu

Resolves: #6618

- [ ] I signed [CLA](https://www.audacityteam.org/cla/)
- [ ] The title of the pull request describes an issue it addresses
- [ ] If changes are extensive, then there is a sequence of easily reviewable commits
- [ ] Each commit's message describes its purpose and effects
- [ ] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [ ] Each commit compiles and runs on my machine without known undesirable changes of behavior

## QA
### Linking
Test these with account unlinked. Execute the steps, and when prompted to the "Share Audio" modal or any variant of it, when clicking "Link Account", the URL opened in your browser should have the specified form, e.g. `https://audio.com/audacity/link?clientId=1741964426607541&<whatever is specified>`.
The same expectation apply if using keyboard shortcuts for these actions instead.
- [ ] Share Audio button: TBD
- [ ] File / Share Audio...:  TBD
- [ ] File / Export Audio / Share to audio.com: TBD
- [ ] Extra / Export / Export as <WAV|MP3|...> / Share to audio.com: TBD
- [ ] File / Save to Cloud: TDB
- [ ] File / Save Project / Save to Cloud: TBD

2024-06-07 14:59 UTC, grliszas14 approved these changes

2024-06-07 14:59 UTC, grliszas14 commented on modules/sharing/mod-cloud-audiocom/CloudProjectOpenUtils.cpp
> +                                AudiocomTrace::OpenFromCloudMenu };
nitpick: formatting

2024-06-07 14:59 UTC, grliszas14 commented on libraries/lib-cloud-audiocom/sync/ProjectCloudExtension.cpp
> +         { AudiocomTrace::ignore, // TODO Is this correct ?
should be ok

2024-06-07 14:59 UTC, grliszas14 commented on modules/sharing/mod-cloud-audiocom/LinkUrlHandler.cpp
> +             // TODO Is this correct?
this should be good too

2024-06-07 15:38 UTC, vsverchinsky commented on src/export/ExportAudioDialog.cpp
> +         audacity::cloud::audiocom::AudiocomTrace /*ignore*/,
Would that build without `lib-cloud-audiocom` dependency?

2024-06-07 15:58 UTC, vsverchinsky requested changes, later dismissed
Can't build without `lib-cloud-audiocom`

2024-06-11 13:50 UTC, LWinterberg approved these changes
LGTM from me and also from Lukas and Arif!

2024-06-17 11:29 UTC, merged