Update 2.4.2 Turkish Translation
audacity/audacity pull request #759
Opened 2021-03-17 11:51 UTC by serkan-maker

# Pull Requests

If you are submitting a pull request, please read https://wiki.audacityteam.org/wiki/GitHub_Pull_Requests

2021-03-17 21:56 UTC, bitigchi commented
Hi, thanks for the translations. I'll continue the review later on, but so far these translations are hardly an improvement over the current ones, moreover some of the previously correct translations are broken. I'd recommend a re-pass over the translations as a whole, and make sure that the "audio" context is preserved.

2021-03-18 06:20 UTC, serkan-maker commented
Hello, I corrected some incorrect translations. I did not make much change in the current translation. The majority was to add accelerators. I fixed the translation of the most parts. I would appreciate it if you report the mistake I made, I would be considered a novice in the translation business. There are also 270 missing translation lines that are not in the .pot file but are available in the interface. These missing lines are present in the .po file but cannot be used.
[audacity_tr.po.zip](https://github.com/audacity/audacity/files/6161718/audacity_tr.po.zip)

2021-03-18 09:01 UTC, bitigchi requested changes

2021-03-18 09:48 UTC, bitigchi requested changes

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Hata. ~% Dosya açılamıyor"
yüzde işaretinden sonra boşluk yok

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "<b>DC Offset:</b> &nbsp;&nbsp;~a"
Ofseti

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Sol: ~a lin, ~a dB | Sağ: ~a lin, ~a dB."
Lin yerine doğ veya doğrusal

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "~aVeri yazılan:~%~a"
Veri şuraya yazıldı:

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Verileri şuraya aktar"
: eksik

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Risset Davul"
Davulu. Altta da aynı terim için tambur denmiş.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +"'Ritim izleme süresi' sıfırdan büyük."
tırnak işaretinden sonra ek gelirse boşlukla ayrılmaz

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "MIDI zayıf vuruş aralığı"
Zayıf vuruşun MIDI perdesi

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Ritim parça süresi"
bazı yerlerde parça, bazı yerlerde iz kullanılmış. hangisi?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "1 - 1000 bars"
aşağıda çubuk varken çoğu yerde bar olarak çevrilmeden bırakılmış

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Notch Filtresi"
süzgeç varken neden filtre? aynı şey ve biri Türkçe

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Stereo suz"
-sXz eki neden ayrı? çift kanallı varken neden stereo?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Hata.~%Seçim, ~a'dan küçük olmalıdır."
çevirirken değişkenlere kesme işaretiyle ek getirilmez, değişkenin büyük ünlü uyumuna uyacağı garantisi yok.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "RMS seviyesi"
düzeyin nesi yanlış?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Vuruş bulmak..."
... varsa süren bir eylemi belirtir. "Vuruşlar bulunuyor..."

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Ritim Bulucu"
vuruş varken ritim ne alaka? ritim rhythm yerine kullanılıyor zaten

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "~aYüzde değerleri % 1000'den fazla olamaz."
% burada yüzde işaretini değil de bir değişkeni belirtiyor olsa gerek. başa yazılması hatalı.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Başla/Bitir"
sonunda as olduğu için başka bir ifade izliyor olsa gerek. Şunun gibi başla/bitir: daha yerinde olabilir. Programdan kontrol edilmeli.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Karart"
Karartma anlaşılır değil. Sesi açarak gir, diğeri için sesi azaltarak çık vb. gibi terimler kullanılmalı.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Solma Uygulanıyor..."
solma? karartma? hangisi?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Solma Uygulanıyor..."
aşağıda belirttiğim gibi açma/azaltma en iyi karşılık fade için duruma göre

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "GNU Genel Kamu Lisansı sürüm 2'nin koşulları altında yayınlandı"
GNU Genel Kamu Lisansı, ikinci sürümün koşulları altında yayımlanmıştır.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "binde octave"
binlerce oktav

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "centihertz"
santihertz

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Komut-Tıklayın"
Command düğmesi olduğu gibi bırakılmalı, klavyelerin üzerinden aynen böyle yazıyor.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "'%s' stereo parçasını böl"
çift kanallı'nın nesi yanlış?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "&Çoklu-görünüm"
bu bağlamda Türkçede tire kullanılmaz, böyle bir kural yok. "Çoklu görünüm"

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Örnek formatın değiştirilmesi"
format kullanılmaya başlansa da biçim hala çok yaygın çevirilerde. değiştirilmesi için bir neden yok

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Örnek formatın değiştirilmesi"
artı çeviri hatalı. "Örnek biçim değiştiriliyor"

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +" önce oynatma veya kaydetme."
doğru olan çeviriyi neden değiştiriyorsunuz?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "k"
" bin" olarak çevrilmeli (boşluğa dikkat). Türkçede 10k diye bir kullanım yok.

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Shift-Sağ-Tık"
yanlış tire kullanımı...

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Çoklu-Araç"
yanlış tire kullanımı

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "2 (Stereo) Kayıt"
kanal neden silindi?

2021-03-18 09:48 UTC, bitigchi commented on locale/tr.po
> +msgstr "Müzik parçası"
müzik ne alaka?

2021-03-18 09:49 UTC, bitigchi commented
I will continue reviewing later on. It will take a while, since I was able to barely review a quarter of the changes.

2021-03-18 12:04 UTC, serkan-maker commented
I corrected the wrong translations you warned
[tr.po.zip](https://github.com/audacity/audacity/files/6163845/tr.po.zip)

2021-03-18 12:12 UTC, bitigchi commented
> I corrected the wrong translations you warned
> [tr.po.zip](https://github.com/audacity/audacity/files/6163845/tr.po.zip)

Thanks for the corrections, I appreciate it. Is it possible to commit your changes here for easier review?

2021-03-18 13:24 UTC, bitigchi requested changes

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Sürüm derlemesi (hata ayıklama düzeyi %d)"
Yayın sürümü/yapısı daha doğru. Sürüm derlemesi anlam bakımından doğru; ancak kavramlar karışıyor.

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Aramak için sürükleyin. Bırakın ve Scrub'a gidin."
Yeni çeviri hatalı, eskisi doğru. Scrub'a gidin bir anlam ifade etmiyor. Aramak da sözlük anlamı olarak doğru olsa da kavram olarak hatalı.

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Hala Audacity'yi başlatmak istiyor musunuz?"
Audacity'yi yine de başlatmak istiyor musunuz?

Çevirirken kavramları çevirmeye sondan başlamak daha doğru. Özne burada Audacity.

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Audacity'den &Çık"
Türkçe karaktere atanan kısayol

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Ön Ayarı &Kullan"
Yeni çeviri hatalı, eskisi doğru

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Bitişte Ses seviyesini azalt"
Tutarsız büyük harf kullanımı

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Makroyu İçe Aktar"
-yu gereksiz

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Makroyu Dışa Aktar"
-yu gereksiz

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Menü Komutu (Parametre Yok)"
Parametresiz

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "%s toplu komutunuz tanınmadı."
anlaşılamadı bu bağlamda doğru. batch için toplu iş olarak kullanılır genelde. tanınmadı doğrudan çeviri oluyor.

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "&İptal"
türkçe karakterde kısayol

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "Kald&ır"
Türkçe karakterde kısayol

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "İ&çe aktar..."
Türkçe karakterde kısayol

2021-03-18 13:24 UTC, bitigchi commented on locale/tr.po
> +msgstr "D&ışa aktar..."
Türkçe karakterde kısayol

2021-03-19 08:12 UTC, serkan-maker commented
incorrect translation corrections
[tr.po.zip](https://github.com/audacity/audacity/files/6169563/tr.po.zip)

2021-03-29 12:22 UTC, closed without merging