CI: macOS: Unblock Xcode version
audacity/audacity pull request #814
Opened 2021-04-19 22:42 UTC by EwoutH

Unblocks the Xcode version in the macOS CI build, since the default is now 12.4.

Practically reverts ef88cb17 now that the GitHub environment was updated, as was intended.

2021-05-27 22:21 UTC, david-shortman commented
Looks like a conflict needs to be resolved, but excited that this is one step closer to apple silicon support!

2021-06-08 01:01 UTC, liilac requested changes
The substantive change itself looks good.

This cannot be merged as is due to changes since this PR was opened, to line [30](https://github.com/audacity/audacity/blob/87652aff2311289a6c1f044bd7034b5c437ac030/.github/workflows/cmake_build.yml#L30) and [31](https://github.com/audacity/audacity/blob/87652aff2311289a6c1f044bd7034b5c437ac030/.github/workflows/cmake_build.yml#L31).
```yml
  DEVELOPER_DIR: /Applications/Xcode_12.3.app/Contents/Developer
  CONAN_USER_HOME: "${{ github.workspace }}/conan-home/"
  CONAN_USER_HOME_SHORT: "${{ github.workspace }}/conan-home/short"
```
Could you rebase your commit?

2021-06-09 08:16 UTC, EwoutH commented
Done!

2021-06-22 01:30 UTC, david-shortman commented
Looks like another conflict cropped up 👀

2021-06-22 07:10 UTC, EwoutH commented
This PR is nothing more than removing a line of code, so I’m closing it for now. A maintainer can easily make this change when he has time himself.

2021-06-22 07:10 UTC, closed without merging