Add new project file format to linux MIME types
audacity/audacity pull request #841
Opened 2021-05-06 21:59 UTC by imciner2

I had to rename the old project MIME type to be a legacy project since the new one isn't XML type and needs a new subclass.

2021-05-07 00:28 UTC, IGBC approved these changes

2021-05-09 13:40 UTC, shoogle requested changes

2021-05-09 13:40 UTC, shoogle commented on src/audacity.xml
> +  </mime-type>
Could we have the newer one at the top?

2021-05-09 13:40 UTC, shoogle commented on images/gnome-mime-application-x-audacity-legacy-project.xpm
> +"48 48 476 2",
Did you find this somewhere or create it yourself? Why not use a more modern image format like SVG?

2022-12-11 13:48 UTC, LWinterberg commented
obsoleted by #3713

2022-12-11 13:48 UTC, closed without merging