New library for strings
audacity/audacity pull request #919
Opened 2021-05-23 11:45 UTC by Paul-Licameli

Separate a shared library from Audacity's source code tree.  But still to do -- correct the Linux build so that the library is installed in the correct folder.  I haven't got the CMake magic words in the first commit right yet.

This library may be re-used by the separate crash reporter executable.

The library contains string utilities, notably:

The classes Identifier and TaggedIdentifier<T> for wrapped string types that are used for internal purposes.

The class TranslatableString containing strings meant for the user to see.

Definitions of macros _, XO, etc. that mark strings for xgettext.

Namespace Languages which contains functions for initializing translation catalogs.

2021-05-23 12:14 UTC, JamesCrook approved these changes
lgtm

2021-05-23 12:46 UTC, Paul-Licameli commented
Now I have fixed the Linux installation.  lib-strings.so goes to the same place as the wxWidgets libraries.

2021-05-24 09:16 UTC, crsib requested changes

2021-05-24 10:49 UTC, Paul-Licameli commented on CMakeLists.txt
> +   set( _LIBRARYDIR ${_EXEDIR} )
See example packages here https://github.com/audacity/audacity/actions/runs/868681745

Yes there is inconsistency on MacOS (lib-strings.so is not in the same place as the wxWidgets libraries) but only that one.  I know it runs just fine.

2021-05-24 10:50 UTC, Paul-Licameli commented on CMakeLists.txt
> +   set( _LIBRARYDIR "${_DEST}/libraries" )
What I wrote for Linux has the correct effect.   All the libraries under lib/audacity in the package

2021-05-24 10:51 UTC, Paul-Licameli commented on CMakeLists.txt
> +   set( _LIBRARYDIR ${_EXEDIR} )
Note that "modules" like mod-script-pipe are not in the same place as libraries nor need be.  They are in a special place examined for drop-ins.

2021-05-24 10:52 UTC, Paul-Licameli commented on libraries/CMakeLists.txt
> +   if( NOT "${CMAKE_GENERATOR}" MATCHES "Visual Studio*")
I was writing by analogy with some lines in modules/CMakeLists.txt which I didn't write

2021-05-24 10:54 UTC, Paul-Licameli commented on libraries/lib-strings/Internat.cpp
> +STRINGS_API const wxString& GetCustomSubstitution(const wxString& str2)
That was put there at 0885fda45971bab64f0600415daa435ec89d90b8 not by me, but I agree.

2021-05-24 10:55 UTC, Paul-Licameli commented on libraries/lib-strings/Languages.h
> +STRINGS_API
I would want to check first that this does not confuse Doxygen when it generates HTML pages

2021-05-24 10:57 UTC, crsib commented on CMakeLists.txt
> +   set( _LIBRARYDIR ${_EXEDIR} )
>Yes there is inconsistency on MacOS (lib-strings.so is not in the same place as the wxWidgets libraries) but only that one. I know it runs just fine.

There will be many more. Both from the 3d party dependencies and our code. I would really love to be consistent here.

2021-05-24 10:58 UTC, crsib commented on CMakeLists.txt
> +   set( _LIBRARYDIR "${_DEST}/libraries" )
Looks like they will go somewhere under libraries in this case

2021-05-24 12:05 UTC, Paul-Licameli commented on CMakeLists.txt
> +   set( _LIBRARYDIR "${_DEST}/libraries" )
Observe where they really did go in artifacts:  https://github.com/audacity/audacity/actions/runs/868681745

This demonstrates that my solution works.

You don't see the complete solution here.  See the cooperating part in libraries/CMakeLists.txt where the linux-only install step moves the .so files from "${_DEST}/libraries into ${_PKGLIB} and it is that destination that matters.

2021-05-27 03:29 UTC, Paul-Licameli commented on CMakeLists.txt
> +   set( _LIBRARYDIR ${_EXEDIR} )
This commit is of course now superceded by your work, Dmitry, and is omitted from the latest rebasing.

2021-05-27 03:30 UTC, Paul-Licameli commented on CMakeLists.txt
> +   set( _LIBRARYDIR "${_DEST}/libraries" )
mooted

2021-05-27 03:30 UTC, Paul-Licameli commented on libraries/CMakeLists.txt
> +   if( NOT "${CMAKE_GENERATOR}" MATCHES "Visual Studio*")
again never mind

2021-05-27 03:50 UTC, Paul-Licameli commented on libraries/lib-strings/Languages.h
> +STRINGS_API
Experiment now shows, Doxygen works either way.  So, I will rewrite as you want it.

2021-05-27 13:26 UTC, crsib approved these changes

2021-05-27 13:52 UTC, merged