Tracking version
audacity/audacity pull request #962
Opened 2021-06-07 15:41 UTC by gera-gas

**New version check.**
This pull request introduces an always-opt-in solution for checking a new Audacity version and further download updates by user actions. This feature will be only enabled if  `audacity_has_updates_check` and `audacity_has_networking` is on.

Dialog example:
![2021-06-07_16-43-48](https://user-images.githubusercontent.com/1660969/121028276-5c33c400-c7b0-11eb-8016-4838d0ff0964.png)

2021-06-08 10:28 UTC, crsib requested changes
There are several places, where documentation and a file opening comment are missing. Please add those.

Also, the case that we have multiple Audacity windows opened should be handled.

2021-06-08 10:28 UTC, crsib commented on src/update/VersionId.h
> +// Initialized of current build version by default.
No longer applies

2021-06-09 11:29 UTC, closed without merging

2021-06-09 18:28 UTC, crsib commented
> I disagree that the case of multiple Audacity windows needs to be handled. This dialog is only meant to happen once when the program begins. The UpdateManager doesn't really depend on the project, except to find a main window.

Originally, there was a problem:
1. User opens a window, gets a notification, dismisses it.
2. User opens another project in a new window and gets the notification again.

I asked Anton to fix it by checking the last time we've shown the update dialog. I haven't looked at #966 yet though

2021-06-09 19:01 UTC, Paul-Licameli commented
Tl;dr: The updater is a long-lived singleton object, with a long period timer.  Projects and windows have shorter lives.  The updater should not be permanently associated with any one project or window.  On Mac There might even be none at the time the updater needs to notify you.